include snazzy.conf

font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font
italic_font      FiraCode Nerd Font
bold_italic_font FiraCode Nerd Font
font_size 22.0
background_opacity 0.7
